version: '3.8'

services:
  web:
    build: ./services/ll_manager
    command: ./entrypoint.sh
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  postgres_data_dev:
