version: '3.8'

services:
  # web:
  #   build: ./services/ll_manager
  #   command: ./entrypoint.sh
  #   ports:
  #     - 5001:5000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:13
    env_file:
      - ./envs/.env.test.local
    ports:
      - "${POSTGRES_PORT}:5432"
