[tool.mypy]
exclude = [
    "^src/migrations/",
]

[tool.black]
line-length = 79

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D100", # Missing docstring in public module
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
]

[tool.ruff.lint.per-file-ignores]
"test_*.py" = [
    "S101" # Use of `assert` detected
]
