name: ll_manager_tests
on: [push]

jobs:
  typechecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Change working directory
        working-directory: ./services/ll_manager
        run: |
          ls
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev_requirements.txt
      - name: Typecheck with mypy
        run: |
          mypy src
