name: ll_manager_tests
on: [push]

jobs:
  typechecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./services/ll_manager
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev_requirements.txt
      - name: Typecheck with mypy
        working-directory: ./services/ll_manager
        run: |
          mypy src

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./services/ll_manager
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Lint with ruff
        working-directory: ./services/ll_manager
        run: |
          ruff check

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./services/ll_manager
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Run unit tests
        working-directory: ./services/ll_manager
        shell: sh
        run: |
          ./scripts/app.sh unit_test
